Xfinity.Constant = {
	SOFTWARE_CATEGORY:[
		["abaqus", "abaqus"], 
		["ansys", "ansys"],
		["castep", "castep"],
		["cfx", "cfx"], 
		["cpmd", "cpmd"],
		["cp2k","cp2k"],
		["default", "default"],
		["dmol3","dmol3"],
		["dyna", "dyna"],
		["dytran","dytran"],
		["esource","esource"],
		["espresso","espresso"],
		["fluent", "fluent"], 
		["gaussian", "gaussian"],
		["hyperworks","hyperworks"],
		["lammps","lammps"], 
		["madymocoupling","madymocoupling"],
		["marc", "marc"],
		["ms","ms"], 
		["nastran", "nastran"],
		["numeca","numeca"], 
		["nwchem", "nwchem"], 
		["pamcrash", "pamcrash"], 
		["radioss", "radioss"],
		["starccm","starccm"],
		["starcd", "starcd"], 
		["vasp","vasp"],
		["wien2k","wien2k"]
	],
	SOFTWARE_TYPE:[
		["仿真计算","1"],
		["前处理","2"],
		["后处理","3"],
		["软件许可","4"]
	],
	UNLOGIN:"用户未登陆!",
	ROLE_SUB_USER:"sub-user",
	ROLE_GROUP_ADMIN:"group-admin",
	ROLE_PUBLISHER:"publisher",
	PROJECT_STATUS:{
		"waitingForApprove":"1",
		"started":"2",
		"notStarted":"3",
		"ended":"4",
		"terminated":"5"
	},
	SUB_USER_CAN_NOT_BUY:"提示：您不具有购买应用的权限，若需购买，请联系组管理员!",
	GROUP_USER_PURCHASED:"提示：您已购买过同集群上的其它应用，购买当前应用免开户费!"
}